# Generated by Django 5.0 on 2024-04-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_master',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=150, unique=True)),
                ('status_id', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='feedbacks_master_byFC',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks by Food Collector',
            },
        ),
        migrations.CreateModel(
            name='feedbacks_master_byUsers',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks by Users',
            },
        ),
        migrations.CreateModel(
            name='FoodCollectionRequests',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('complainant_name', models.CharField(max_length=150)),
                ('complainant_contact_no', models.IntegerField()),
                ('complainant_email', models.EmailField(max_length=254)),
                ('complainant_address', models.TextField(max_length=1000)),
                ('detailed_description', models.TextField(max_length=10000)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('changed_by', models.CharField(blank=True, default=' ', max_length=100000, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_area+', to='FCRs.area_master', to_field='area_name')),
            ],
            options={
                'verbose_name_plural': 'FoodCollectionRequests',
            },
        ),
    ]
